repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: mixed-line-ending
        args: [--fix=lf]  # Force Unix line-endings

-   repo: https://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
    -   id: go-fmt
    -   id: go-imports
    -   id: go-vet
    -   id: go-lint
    -   id: go-unit-tests

-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
    -   id: shellcheck
        args: [-e, SC1090]  # Ignore source file not found

-   repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
    -   id: yamllint
        args: [--format, parsable, --strict]
