extensions:
  health_check: {}

receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      memory: {}
      cpu: {}

processors:
  batch: {}

exporters:
  debug:
    verbosity: detailed

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [debug]