{{- if eq .Values.mode "fanout" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fanout
  namespace: {{ .Release.Namespace }}
  labels:
    app: otel-fanout
    release: {{ .Release.Name }}
    mode: {{ .Values.mode }}
spec:
  type: ClusterIP
  ports:
    - port: 4317
      targetPort: otlp-grpc
      protocol: TCP
      name: otlp-grpc
    - port: 8888
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: otel-fanout
    release: {{ .Release.Name }}
{{- end }}
