name: Benchmarks

on:
  schedule:
    - cron: "0 4 * * *" # Nightly at 4 AM UTC
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main
    paths:
      - 'bench/**'
      - 'core/**'
      - 'apps/**'
      - 'infra/**'
      - 'build/**'
      - 'scripts/**'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - '.github/workflows/bench.yml'

jobs:
  run-benchmarks:
    name: Run E2E Benchmark
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # For git commands to determine version/tag

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Set up dependencies
        run: |
          echo "use (./core/reservoir ./bench/runner ./)" > go.work
          go work sync

      - name: Set up KinD
        uses: engineerd/setup-kind@v0.9.0
        with:
          version: v0.20.0
          config: infra/kind/kind-config.yaml

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Generate image tag
        id: image_tag
        run: |
          # Use short SHA for image tag in CI benchmark runs
          IMAGE_TAG_SHA=$(git rev-parse --short HEAD)
          echo "TAG=${IMAGE_TAG_SHA}" >> $GITHUB_OUTPUT

      - name: Run Benchmarks
        run: |
          # Run benchmarks using the new streamlined script
          bash scripts/run-benchmark.sh \
            --version ${{ steps.image_tag.outputs.TAG }} \
            --duration 15m \
            --profiles max-throughput-traces,tiny-footprint-edge \
            --mode kind \
            --license ${{ secrets.BENCHMARK_NEW_RELIC_KEY || 'DUMMY_FOR_BENCHMARK' }}
        env:
          NEW_RELIC_KEY: ${{ secrets.BENCHMARK_NEW_RELIC_KEY }}

      - name: Upload KPI Results CSV
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kpi-results
          path: /tmp/kpi_*.csv
          retention-days: 7

      - name: Upload Benchmark Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-reports
          path: benchmark-results-*
          retention-days: 7