name: CI Pipeline

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run tests for all modules
        run: |
          # Setup Go workspace for multi-module testing
          echo "use (./core/reservoir ./)" > go.work
          make test

  build:
    name: Build Image
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=latest" >> $GITHUB_OUTPUT
          fi

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/docker/Dockerfile.multistage
          build-args: |
            NRDOT_VERSION=v0.91.0
            RS_VERSION=${{ steps.version.outputs.VERSION }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/nrdot-reservoir:${{ steps.version.outputs.VERSION }}