name: Lab – nightly matrix
on:
  schedule:
    - cron: '0 3 * * *'     # 03:00 UTC daily
  workflow_dispatch:        # manual trigger

jobs:
  soak:
    strategy:
      matrix:
        profile: [balanced, optimized, lean, micro]
    runs-on: ubuntu-latest
    timeout-minutes: 120
    name: soak-${{ matrix.profile }}
    env:
      PROFILE:  ${{ matrix.profile }}
      NR_KEY:   ${{ secrets.NR_LICENSE_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Patch config for hosted runner
        run: |
          sed -i 's/hostmetrics_ultra:/hostmetrics_ultra:\n  disable_scrapers:\n    - process.disk\n    - process.open_fds\n    - process.threads/' config.yaml
      - uses: ./.github/actions/start-lab
        with:
          nr-license-key:   ${{ env.NR_KEY }}
          profile:          ${{ env.PROFILE }}
          duration-minutes: 90